version: '3.9'

services:
  web:
    container_name: dockerdev
    build: ./
    ports:
      - "8080:8080"
    environment:
      DD_DB_HOST: db
    command: /server
    depends_on:
      - db

  db:
    container_name: dockerdev-db
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: treasure
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql